version: '3.5'
services:

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    networks:
      - dbazeinfrab
    restart: always
    environment:
      - TZ=Asia/Bangkok
      - MYSQL_DATABASE=dbaze
      - MYSQL_ROOT_PASSWORD=aa111111
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
      - '--max-connections=512'
      - '--innodb-buffer-pool-size=256M'
      - '--innodb-log-buffer-size=32M'
      - '--innodb-file-per-table=1'
    ports:
      - '3306:3306'
    volumes:
      - './database:/var/lib/mysql'
      - './init.sql:/docker-entrypoint-initdb.d/init.sql'

  dbaze:
    image: wordpress:latest
    container_name: dbaze
    networks:
      - dbazeinfraf
      - dbazeinfrab
    restart: always
    environment:
      - TZ=Asia/Bangkok
      - WORDPRESS_DB_HOST=mariadb:3306
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_NAME=dbaze
      - WORDPRESS_DB_PASSWORD=aa111111
    ports:
      - '8080:80'
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./storage/d-baze:/var/www/html/d-baze
    depends_on:
      - mariadb

  tea2one:
    image: wordpress:latest
    container_name: tea2one
    networks:
      - dbazeinfraf
      - dbazeinfrab
    restart: always
    environment:
      - TZ=Asia/Bangkok
      - WORDPRESS_DB_HOST=mariadb:3306
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_NAME=tea2one
      - WORDPRESS_DB_PASSWORD=aa111111
    ports:
      - '8081:80'
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./storage/tea2one:/var/www/html/tea2one
    depends_on:
      - mariadb
  
  nginx:
    image: nginx:alpine
    container_name: nginx
    networks:
      - dbazeinfraf
    restart: always
    environment:
      - TZ=Asia/Bangkok
    ports:
      - '80:80'
    volumes:
      - ./certs:/opt/certs:ro
      - ./config/d-baze.me.conf:/etc/nginx/conf.d/default.conf:ro
      - ./config/tea2one.conf:/etc/nginx/conf.d/tea2one.conf:ro
      - ./config/nobi.conf:/etc/nginx/conf.d/nobi.conf:ro
      - ./storage/d-baze:/var/www/html/d-baze:ro
      - ./storage/nobi:/var/www/html/nobi
      - ./storage/tea2one:/var/www/html/tea2one:ro
    depends_on:
      - dbaze
      - tea2one
      
networks:
  dbazeinfrab:
    name: dbazeinfrab
  dbazeinfraf:
    name: dbazeinfraf
