version: "2"

services:
  mariadb:
    image: "docker.io/bitnami/mariadb:latest"
    container_name: mariadb
    volumes:
      - "mariadb_data:/bitnami/mariadb"
    ports:
      - "127.0.0.1:3306:3306"
    env_file:
      - .env wordpress:
    depends_on:
      - mariadb

  wordpress:
    image: "local/wordpress-nginx:latest"
    container_name: wordpress
    volumes:
    - "wordpress_data:/bitnami/wordpress" 
    - "../:/bitnami/wordpress/wp-content/themes/develop-theme:ro"
    - "./source/.empty/0:/bitnami/wordpress/wp-content/themes/develop-theme/.git"
    - "./source/.empty/1:/bitnami/wordpress/wp-content/themes/develop-theme/.deployment"
    - "./source/.empty/2:/bitnami/wordpress/wp-content/themes/develop-theme/.development"
    - "./source/.empty/3:/bitnami/wordpress/wp-content/themes/develop-theme/.deployment-wordpress"
    ports:
      - "127.0.0.1:80:8080"
      - "127.0.0.1:443:8443"
    env_file:
      - .env