name: deploynaja
on:
  push:
    branches:
      - master
    steps:
      - name: down
        run: cd compose/d-baze.me
      - name: down
        run: docker-compose down --remove-orphans
      - name: upd
        run: docker-compose up -d