name: deploynaja
on: push
jobs:
  dockerdeploy:
    runs-on: ubuntu-latest
    steps:
      - name: path
        run: pwd
      - name: list
        run: ls -la
      # - name: down
      #   run: cd /home/system/compose/d-baze.me
      # - name: down
      #   run: docker-compose down --remove-orphans
      # - name: upd
      #   run: docker-compose up -d